# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '浏览器.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import QUrl
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtWebEngineWidgets
import sys
from PyQt5.QtCore import QUrl
from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEngineProfile
from PyQt5.QtWidgets import QApplication, QWidget, QVBoxLayout, QPushButton

global Text
Text = ""
global Cookoie
Cookie = ""


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(559, 355)
        self.widget = QtWebEngineWidgets.QWebEngineView(Form)
        self.widget.load(QUrl("https://qun.qq.com/member.html#gid=827941147"))
        self.widget.setGeometry(QtCore.QRect(10, 10, 450, 335))
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 330, 551, 41))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton_15 = QtWidgets.QPushButton(self.widget)
        self.pushButton_15.setGeometry(QtCore.QRect(220, 275, 141, 51))
        self.pushButton_15.setStyleSheet("QPushButton{\n"
                                         "    border-image: url(3.png);\n"
                                         "    border-radius: 4px;\n"
                                         "    font: 9pt \"Microsoft YaHei\";\n"
                                         "    color:white;\n"
                                         "    border:1px;\n"
                                         "    border-right: transparent;\n"
                                         "}\n"
                                         "QPushButton:hover{\n"
                                         "    border-image: url(2.png);\n"
                                         "}\n"
                                         "QPushButton:pressed{\n"
                                         "    \n"
                                         "    border-image: url(1.png);\n"
                                         "}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../.designer/backup/右箭头.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_15.setIcon(icon)
        self.pushButton_15.setObjectName("pushButton_15")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(450, 11, 101, 351))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Qun Login"))
        self.pushButton_15.setText(_translate("Form", "验证"))
        self.pushButton_15.raise_()
        self.pushButton_15.clicked.connect(self.__getCookieRunJs)

    def __getCookieRunJs(self):
        runJs = '''
        function getCookie(){return document.cookie}
        getCookie();
        '''
        self.widget.page().runJavaScript(runJs, self.__getCookieByJs)

    def __getCookieByJs(self, result):
        cookie = result
        print(cookie)
        self.widget.hide()
        target = "skey="
        location = cookie.index(target)
        target2 = ";"
        location2 = cookie[location + 5:].index(target2)
        skey = cookie[location + 5:][:location2]
        print("skey: " + skey)

        def bkn(skey):
            e = skey
            t = 5381
            n = 0
            o = len(e)
            while n < o:
                t += (t << 5) + ord(e[n])
                n += 1
            return t & 2147483647

        print("BKN: " + str(bkn(skey)))
        import time
        import requests
        import json
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36",
            "Cookie": cookie
        }
        end = 40
        start = end
        for i in range(1, int(1000 / 40) + 1):
            st = start * i - 40
            en = start * i
            data = {'gc': 827941147, 'st': st, 'end': en, 'sort': 0, 'bkn': bkn(skey)}
            response = requests.post("https://qun.qq.com/cgi-bin/qun_mgr/search_group_members", data=data,
                                     headers=headers, verify=False)
            qqJson = json.loads(response.text)
            global Text
            Text = Text + str(qqJson)
        print(Text)
        res = "3605298273" in Text
        if res == True:
            print("验证成功.")
        else:
            print("验证失败.")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
